export enum ErrorCode {
  // General errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  // Validation errors
  INVALID_ARGUMENT = "INVALID_ARGUMENT",
  MISSING_ARGUMENT = "MISSING_ARGUMENT",

  // Permissions
  MISSING_PERMISSIONS = "MISSING_PERMISSIONS",
  BOT_MISSING_PERMISSIONS = "BOT_MISSING_PERMISSIONS",

  // External services
  TIMEOUT = "TIMEOUT",
  API_ERROR = "API_ERROR",
  RATE_LIMITED = "RATE_LIMITED",

  // Discord-specific
  USER_NOT_FOUND = "USER_NOT_FOUND",
  COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND",
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",

  // Database
  DB_QUERY = "DB_QUERY",
  DB_CONNECTION = "DB_CONNECTION",
}
